# Generated by Django 2.0.6 on 2018-07-21 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(null='static\\images\\img1', upload_to='static'),
        ),
    ]
